### ISSUE TITLE
Spring 개념에 관련해서 질문이 있습니다

### ISSUE THREAD

**Issue by chris-conbus** [thecodinglive/JPub-JavaWebService#10]
인터넷을 보면 Controller에서 하는 일과 service에서 하는 일 따로 dto를 만들어서 코딩을 하던데 그 각자의 역할이 궁금 합니다.

**Comment by sjyun** [comment]
안녕하세요.

계층형 아키텍처라는 게 있습니다.

혹시 네트워크에서 OSI 7 Layer에 대해 배운 적 있나요?

소프트웨어에서의 계층형 아키텍처나 네트워크에서 OSI 7 Layer나 모두 목적은 동일하게
층별로 역할을 나누는 것입니다.

그리고 Controller, Service 이런 구분은 스프링에서도 어노테이션을 제공하는데요

특정 url을 호출했을 때 HTTP 요청(Request)를 받고 HTTP 응답(Response) 를 주는 역할을 하는 클래스들에
Controller 어노테이션을 사용하고 Service는 DB에 직접 요청을 하는 Repository 들을 모으고 감싸서 기능을 제공하는 역할을 합니다.

자세한 내용은
https://www.edwith.org/boostcourse-web/lecture/16767/
이 강좌를 보시면 도움이 될 거 같아요
