### ISSUE TITLE
[질문아니에요]프로젝트 생성방법

### ISSUE THREAD

**Issue by pollra** [thecodinglive/JPub-JavaWebService#11]
혹여나 저처럼 스프링부트이널라이저로 삽질하실분들을 위한 코멘트입니다.(인텔리제이 기준)
file - new project - gradle - sdk설정 - groupid/artifactid 설정 - 예제 프로젝트에서 build.gradle 복붙 - 
코드 작성 후 gretty - appStartWar 실행
그럼 잘 실행됩니다..
이게 뭐라고 1시간동안 삽질을 했는지.. ㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by sjyun** [comment]
ㅠㅠ 고생하셨네요
공유 감사합니다.

안 그래도 서블릿 개발환경 쪽 설정이 어렵다는 문의가 있어서
https://www.youtube.com/watch?v=liLBiaCXvZU&t=4s

동영상 올려놓긴 했는데 소개가 늦었네요

**Comment by SuperHappyChocolateCake** [comment]
안녕하세요 저자님 솔직히 화가 납니다. 책을 1페이지부터 찬찬히 읽어봐도 2장은 시작부터 막히니 설명이 너무 부족한게 아닌가 싶네요 베타리더님들은 책을 안읽어보았나요?

**Comment by SuperHappyChocolateCake** [comment]
14페이지에 라이브러리 의존성을 추가할 때는 이클립스나 인텔리제이와 같은 도구에서 자동완성을 이용해서 추가 할수(중략) 이 절에서는 개발도구의 도움을 받지 않고 사이트에서 검색을 통홰 추가하는 방법을 알아보자 라고 되어있는데 이 부분 설명에서 저는 인텔리 제이나 이클립스 같은 개발도구를 쓰지 말라는 뜻인줄 알았습니다 왜냐하면 14페이지 이전에는 이클립스나 인텔리제이를 소개 하거나 설치를 한다는둥의 언급이 한마디도 없었거든요

**Comment by pollra** [comment]
궁금하신게 있다면 찾아보면 되시고 찾지 못하시면 질문하시면 됩니다.
만약 아무리 찾아도 모르겠고, 본인의 질문에 대답해줄사람이 없다고 한다면.
그 책은 본인에게 맞지 않는 책으로서, 조금 더 쉽게 설명되어있는 책을 구입하셔야합니다.

**Comment by myDaebbang** [comment]
이것은 책이 아니다. 예제를 따라 할 수가 없다. 저 위에 계신 분...궁금한 것 찾아보라고..그럼 책을 사는 이유가 무엇인가?

**Comment by sjyun** [comment]
@SuperHappyChocolateCake 안녕하세요 확인이 늦었습니다.
인텔리제이 사용방법은 부록으로 뒷장에 있고
14p 내용은 이해하신 것처럼 개발도구 없이 코드 다운받아서 실행하거나
직접 타이핑해서 확인할 수 있습니다.


그리고 이 책은 자바 웹개발을 위한 입문서로, 대상 독자를 자바나 c언어를 배운 사람들을 대상으로 썼습니다.
http://www.yes24.com/Product/Viewer/Preview/61793313

시중에 자바 개발 입문서 책이 많고, 대부분 자바 입문서에서 개발 툴 내용도 다루기 때문에
배제하였습니다.  진행하시면서 필요하신 내용 있으면 말씀해주세요.

**Comment by myDaebbang** [comment]
일단 부록에 있는 인텔리제이 사용방법은 캡처 떠 놓은 것처럼 글자가 보이질 않습니다. 
최소한 백그라운드 색상과 글자 색상을 변경해서 좀 잘 보이도록 최소한 독자에 대한 배려가 있어야 한다고 봅니다. 물론 동영상 강좌도 보았으나 이클립스나 STS만 사용하다가 인텔리제이로 해보고 싶은 생각으로 이 책을 구매했습니다. 

적어도 동영상이나 ppt로 인텔리제이에서 gradle 프로젝트 생성하는 것에 대한 설명은 있어야 한다고 봅니다. 주어진 소스를 임포트하여 실행하는 것은 의미가 없다고 봅니다. 

프로젝트 하다가 이 새벽 시간에 책을 보면서 공부를 하는데 인터넷 뒤져가면서 할 바에야 뭐하러 책을 구매하겠습니까? 인터넷 보면서 하지....

적어도 독자에 대한 최소한의 배려라면

IntelliJ Community에서 개발환경설정 그리고 첫 예제인 서블릿을 gradlew가 아닌 IntelliJ에서 빌드 후 
브라우저에서 확인할 수 있는 그런 배려는 해주어야 그 다음 예제를 따라 가지...이건 뭐..웹 처음 개발하는
사람은 도저히 따라 갈 수가 없을 것 같습니다.

실무로 웹개발을 한 사람도 첫 예제부터 막히는데...뭘 하라는 건지?

**Comment by myDaebbang** [comment]
참고로 전 프로그램 개발 경력 20년 이상이고 실무에서 PM을 수행하고 있습니다. 
부록에 있는 것은 예제 실행 방법이지 IntelliJ로 개발환경 설정은 아니라고 봅니다.
저자 께서는 저 캡처 떠놓은 글들이 보이시나요? 전 도저히 보이질 않습니다.

**Comment by myDaebbang** [comment]
전 이 책을 Spring Data JPA, 액추에이터를 활용한 모니터링, 클라우드 서비스를 이용한 배포까지 라는 이 문구때문에 구매를 했습니다. 자바를 모르는것도 아니고 스프링, 마이바티스를 모르는 것도 아니고....

그런데 제가 보기에는 적어도 입문하는 사람이 따라할 수 있도록 최소한의 배려가 없다는 뜻입니다.

**Comment by pollra** [comment]
** 책 구매 목적이 뭔가요? **
 제가 책을 구매하는 목적은 ‘제가 모르는것의 지식을 좀더 편하게 습득하기 위함’ 입니다.
누군가 그 지식에 대한것을 한글로 정리해둔것을 읽기 위해 책을 삽니다.
인터넷의 레퍼런스는 번역이 안되어있으며 누군가 정리해놓은 블로그 역시 믿을만한게 못됩니다.
구글의 번역기도 있지만 문맥이 말끔하지 못하고 저자가 의도한 바를 명확히 전달하지 못합니다.

** 모르면 검색해야죠 **
아무리 여기다가 답글을 단다고 해도 본인이 모르는 지식이 채워지진 않습니다. 답글 달 시간에 본인의 수준에 맞는, 본인의 입맛에 맞는 책을 구매하셔서 보는게 지식습득에 훨씬 효율적이라 봅니다.
 지식을 본인의 입맞에 맞게 떠먹여주는 사람이 없으면 스스로 떠먹어야죠.

책이 마음에 안든다면 네이버 별점을 깎으면 그만입니다.
제가 해결한 문제중 하나를 글로 작성해놓은 이곳에서 대화의 장을 열 필요가 전혀 없습니다.

**Comment by pollra** [comment]
책 구매 목적이 뭔가요?
 제가 책을 구매하는 목적은 ‘제가 모르는것의 지식을 좀더 편하게 습득하기 위함’ 입니다.
누군가 그 지식에 대한것을 한글로 정리해둔것을 읽기 위해 책을 삽니다.
인터넷의 레퍼런스는 번역이 안되어있으며 누군가 정리해놓은 블로그 역시 믿을만한게 못됩니다.
구글의 번역기도 있지만 문맥이 말끔하지 못하고 저자가 의도한 바를 명확히 전달하지 못합니다.

모르면 검색해야죠 
책이 마음에 안든다면 네이버에서 낮은 별점을 주고 한줄평을 적으면 그만입니다. 그리고 다른책으로 지식을 습득하면 되죠.

**Comment by pollra** [comment]
@myDaebbang 
책을 사는 이유가 뭔가요?
누군가 해당 내용에 대해 한글로 정리해놓은 글을 보기 위해 삽니다
대부분의 블로그는 믿을만 하지 못합니다. (추측성 글, 글쓴이의 수준을 모르는 상황에서의 글쓴이 개인적인 견해, 책임이 없는 지식전파)
도큐먼트는 영어로 되어있으며 번역기로 번역해보아도 해당 글을 작성한 글쓴이의 의도를 명확하게 전달하지 못합니다.
 그에 비해 책은 금전이란 대가를 지불하고 얻는 지식의 조각으로서 제가 모르는 부분에 대한 정상적인 키워드를 알 수 있습니다
 책이 안좋다고 이곳에서 백날 이백날 댓글을 다는것보다 이 책에서 얻은 키워드를 가지고 자신의 수준에서 이해하기 쉬운 책을 구매하여 학습하는것이 훨씬 이롭습니다.
