### ISSUE TITLE
github 예제 파일 다운로드 받아 import 하는데 어려움이 있습니다.

### ISSUE THREAD

**Issue by ideal-JJ** [thecodinglive/JPub-JavaWebService#12]
sts 를 이용하여 예제 파일을 import 하려고 합니다.

아래 두 이미지와 같이 Existing Projects into Workspace를 이용하여 경로를 설정을 했는데요.
1.img
![image](https://user-images.githubusercontent.com/40516663/49422097-c9c49b00-f7d5-11e8-9cfc-ec70d5078786.png)
2.img
![image](https://user-images.githubusercontent.com/40516663/49422265-8fa7c900-f7d6-11e8-80a9-1b849a3b7275.png)

이렇게 했더니....
평소대로라면 선택한 프로젝트 하위에 챕터 폴더가 주르륵 떠야 하는데 
아래 이미지처럼 아무것도 뜨지 않습니다.
3.img
![image](https://user-images.githubusercontent.com/40516663/49422163-14deae00-f7d6-11e8-9086-efdefa45930e.png)

import 는 어떻게 하는지 궁금합니다 ㅠㅠ

**Comment by sjyun** [comment]
안녕하세요.

캡쳐해주신 화면 중에 첫번째 화면을 보시면 general 밑에 4번째에 Gradle이 있어요 gradle을 선택하시고 진행해보세요

처음에는 라이브러리 다운 받느라 시간이 오래 걸려요.
![gradle-import](https://user-images.githubusercontent.com/1390605/49423500-0b0b7980-f7db-11e8-9481-91ffb41db749.png)


그리고 로컬에서 개발환경을 세팅하지 않고도 실습하실 수 있도록
구름ide에서 온라인으로 실습하는 방법도 준비해두었습니다.
https://www.youtube.com/watch?v=liLBiaCXvZU&t=4s
