### ISSUE TITLE
ch02 서블릿 초기화와 init 메서드

### ISSUE THREAD

**Issue by Rico-0** [thecodinglive/JPub-JavaWebService#13]
grandlew appStartWar로 실행하라고 하는데 이게 무슨 프로그램인지 모르겠어요 ㅠㅠ

![image](https://user-images.githubusercontent.com/45986958/50199237-21950180-0393-11e9-89be-5483d5f61e3a.png)

명령어를 추가해서 실행시켜 봤는데 안 되더라고요

**Comment by sjyun** [comment]
안녕하세요. 
로컬에서는 gradle이 설치되어 있지 않은 경우가 있어서 gradlew appStartWar로 안내해드렸는데요
명령어 추가하실 때 구름ide에는 그래들이 설치되어 있어서
 **gradle appStartWar**로   실행하시면 되실 거에요

**Comment by Rico-0** [comment]
답변 감사합니다! 근데 사이트에서 연결을 거부했다는 메시지가 출력되네요 ㅠㅠ 방화벽 문제인 듯 한데, 어떻게 해결하면 될지 이것도 혹 알려주실 수 있을까요?

**Comment by sjyun** [comment]
그러면 첨부된 이미지처럼 'gradle appStart' 실행하시고 우측에 도메인 주소를 클릭해보세요
캡쳐된 이미지처럼 정상적으로 실행이 되서 http://localhost:8080 이 표시되면 우측칸에 http://servlet-ibxiu.run.goorm.io를 클릭하시면 됩니다.
![grettyrun](https://user-images.githubusercontent.com/1390605/50200028-6f136d80-0397-11e9-9b0c-a9adf003c56a.png)

**Comment by Rico-0** [comment]
앗, 그렇게 했더니 되네요. 다음에도 궁금한 게 생기면 또 질문하러 오겠습니다. 감사합니다~

**Comment by Rico-0** [comment]
![get](https://user-images.githubusercontent.com/45986958/50264223-04c50080-045d-11e9-8204-5308d0ae69ad.PNG)

안녕하세요 :) 다시 질문 드립니다만 저기에서 원래는 입력받은 사이트명이 나와야 하는데, 자꾸 get 메서드가 호출되어 hello만 출력되는데 이유가 혹시 있나요? 책에 있는 소스를 그대로 받아서 친 건데 :0

**Comment by sjyun** [comment]
안녕하세요. 
System.out.println 메소드로 출력한 내용은 콘솔에 출력되기 때문에, 웹페이지에는 표시되지 않습니다.
화면에 출력되는 내용을 변경하고 싶으시면
resp.getWriter().println("내용"); 부분을 수정하시면 되어요
