### ISSUE TITLE
12장 import후의 문제

### ISSUE THREAD

**Issue by JiSeungHoon** [thecodinglive/JPub-JavaWebService#14]
gradle프로젝트로 import를 하였습니다.
하지만 controller부분의 log함수와 model- vo의 getter setter부분에 에러가 나는데..lombok의 문제인지 잘모르겠네여 ㅠㅠ 저는 sts로 import를 하였습니다.

**Comment by JiSeungHoon** [comment]
![image](https://user-images.githubusercontent.com/21056498/51093578-74be7080-17e8-11e9-8471-1fa3db9462e2.png)

**Comment by sjyun** [comment]
안녕하세요. 답변이 늦어서 죄송합니다.

https://ransu.tistory.com/entry/EclipseMars-lombok-%EC%84%A4%EC%B9%98

요 블로그 참고하셔서 lombok jar를 별도로 다운받은담에  추가 설정 부탁드려요
