### ISSUE TITLE
2.5챕터 FrontContrller.java 관련하여 질문 드립니다

### ISSUE THREAD

**Issue by chris-conbus** [thecodinglive/JPub-JavaWebService#4]
제가 직접 코드를 쳐봣는데  java.lang.NullPointerException 오류가 나길래 예제 코드를 받아다가 직접 복붙 해봐도 같은 오류가 납니다... 이유가 뭘까요 try로 찍어보니까 값이 안 들어가고 null만 있긴 하던데...
![image](https://user-images.githubusercontent.com/34623431/43560623-63b1feea-964e-11e8-9f65-db33285e28f6.png)

**Comment by sjyun** [comment]
/WEB-INF/command.properties 이 파일이 있어야 되는데요.

그리고 localhost:8080/controller?=cmd=home 처럼 파라메터를 넘겨줘야 합니다.
