### ISSUE TITLE
17페이지 2.2에 gradlew appStartWar

### ISSUE THREAD

**Issue by nine456** [thecodinglive/JPub-JavaWebService#5]
제목그대로 gradlew appStartWar로 실행한다는것이 무엇인지 모르겠습니다.

**Comment by jjh75607** [comment]
저도 몰라서 이 질문 올렸었는데 ㅎㅎ..
![image](https://user-images.githubusercontent.com/34623431/43698739-7f8c2e7a-9986-11e8-96e7-5f6a5ec9f430.png)
오른쪽에 gradle로 들어가셔서 Tasks << 이거 여시면 있습니다 ㅎ..

**Comment by sjyun** [comment]
예 ch02 프로젝트가 있는 경로에서 windows+R => cmd 입력하시면 나오는 커멘드 창에서
gradlew appStartWar를 뜻하는 거였고요, jjh75607 님이 답변주신것처럼 캡쳐화면에서 intellj 로 실행해도 됩니다.
