### ISSUE TITLE
부록 내용대로 빌드시

### ISSUE THREAD

**Issue by parkshinwoo** [thecodinglive/JPub-JavaWebService#6]
2시간이 지났는데도 빌드가 끝나지를 않네요..
도중에 stop 시켰는데 원래 이렇게 빌드 시간이 긴건가요?

**Comment by sjyun** [comment]
아니요 2시간은 너무 기네요.  File -> Invalidate Caches / Restart 를 하면 캐시가 삭제되고 재시작되는데요

말씀하신 부분은 빌드뿐만 아니라 라이브러리 싱크를 맞추려고 백그라운드로 뭔가 계속 실행되어서 그럴 수 있습니다.

**Comment by sjyun** [comment]
http://forgiveall.tistory.com/405
인텔리제이에 heap size를 늘려보세요.  2기가 정도로 늘려보시면..

설정된 메모리가 너무 작아서 느릴 수도 있어요.
