### ISSUE TITLE
멀티 db셋팅

### ISSUE THREAD

**Issue by ksycafe** [thecodinglive/JPub-JavaWebService#7]
P.202 내용에서 
spring.datasource.url=jdbpc......
설정에서 mariadb가 2개이상일 경우에 설정은 어떻게 하나요?
궁금합니다.

**Comment by sjyun** [comment]
가장 간단한 방법은 Connection 객체를 2개 만드는 겁니다.
mysql.datasource.masterurl=
mysql.datasource.salveurl= 처럼 프로퍼티를 2개 만들고
connection 객체에서 2개의 프로퍼티를 각각 할당하고
repository 레이어도 2개 만들면 됩니다.

https://www.slideshare.net/junghaelee10/mariadb-58514643
또는 위 링크처럼 mariadb를 MMM( Multi Master Replication)으로 구성하신다음에 사용할 수 있습니다.
